language: generic

os:
  - linux
  - osx
  - windows

addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - git
    - libsecret-1-dev  

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh
